export { calculateWeaponWorkshopDiscount, calculateTrainingFacilityDiscount, applyDiscount, calculateWeaponResaleRate, applyResaleRate } from './discounts';
export { getCapForLevel, ACADEMY_CAP_MAP } from './academyCaps';
export { calculateBaseCost, calculateDiscountedUpgradeCost, calculateUpgradeCostRange } from './upgradeCosts';
export { ROBOT_ATTRIBUTES, isRobotAttribute, type RobotAttribute } from './robotAttributes';
export {
  calculateRepairCost,
  calculateRobotRepairCost,
  calculateRepairBayDiscount,
  sumAttributes,
  MANUAL_REPAIR_DISCOUNT,
  type RepairCostRobot,
} from './repairCost';
export {
  calculateRefinementCost,
  getRefinementMagnitudeRange,
  validateRefinementSlotAvailable,
  validateAttributeStackCap,
  validateAttributeOnWeapon,
  validateShieldCompatibility,
  applyRefinementsToWeapon,
  calculateRankPrefix,
  formatWeaponDisplayName,
  type RefinementTier,
  type RankPrefix,
  type RefinementRow,
  type EffectiveWeaponStats,
  type WeaponLike,
  type ValidatorResult,
} from './weaponRefinement';
export {
  computeBattleStatistics,
  createRobotStats,
  type BattleLogEvent,
  type BattleStatistics,
  type RobotCombatStats,
  type TeamCombatStats,
  type DamageFlow,
  type HandStats,
  type CounterStats,
  type HitGrades,
} from './battleStatistics';
export {
  LOADOUT_BONUSES,
  STANCE_MODIFIERS,
  BASE_HP,
  HP_MULTIPLIER,
  SHIELD_MULTIPLIER,
  calculateAttributeBonus,
  getLoadoutBonus,
  getStanceModifier,
  calculateEffectiveStat,
  calculateEffectiveStats,
  calculateMaxHP,
  calculateMaxShield,
  getLoadoutModifiedAttributes,
  formatLoadoutName,
  getLoadoutDescription,
  getAttributeDisplay,
  isValidStance,
  isValidYieldThreshold,
  type WeaponBonuses,
  type WeaponInventoryLike,
  type RobotStatsInput,
  type TuningAttributeMap,
} from './robotStats';
