/**
 * Feature: security-audit-guardrails, Property 7: JWT expiration bound
 *
 * **Validates: Requirements 3.6**
 *
 * For any JWT generated by the generateToken function, the exp claim shall be
 * at most 24 hours (86,400 seconds) after the iat claim.
 */
import fc from 'fast-check';
import jwt from 'jsonwebtoken';
import { generateToken, UserForToken, TokenPayload } from '../src/services/auth/jwtService';

describe('Feature: security-audit-guardrails, Property 7: JWT expiration bound', () => {
  const jwtSecret = process.env.JWT_SECRET || 'dev-secret-change-in-production';

  // Save and restore JWT_EXPIRATION to avoid test pollution
  const originalExpiration = process.env.JWT_EXPIRATION;

  afterAll(() => {
    if (originalExpiration !== undefined) {
      process.env.JWT_EXPIRATION = originalExpiration;
    } else {
      delete process.env.JWT_EXPIRATION;
    }
  });

  it('exp - iat <= 86400 for any generated token (default expiration)', () => {
    // Ensure default expiration is used
    delete process.env.JWT_EXPIRATION;

    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 100000 }),           // userId
        fc.stringMatching(/^[a-zA-Z0-9_]{3,20}$/),     // username
        fc.constantFrom('user', 'admin'),                // role
        fc.integer({ min: 0, max: 100 }),                // tokenVersion
        (userId, username, role, tokenVersion) => {
          const user: UserForToken = {
            id: String(userId),
            username,
            role,
            tokenVersion,
          };

          const token = generateToken(user);
          const decoded = jwt.verify(token, jwtSecret) as TokenPayload;

          expect(decoded.iat).toBeDefined();
          expect(decoded.exp).toBeDefined();

          const diff = decoded.exp! - decoded.iat!;
          // exp - iat must be at most 86400 seconds (24 hours)
          expect(diff).toBeGreaterThan(0);
          expect(diff).toBeLessThanOrEqual(86400);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('exp - iat <= 86400 for any generated token (explicit 24h expiration)', () => {
    process.env.JWT_EXPIRATION = '24h';

    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 100000 }),
        fc.stringMatching(/^[a-zA-Z0-9_]{3,20}$/),
        fc.constantFrom('user', 'admin'),
        fc.integer({ min: 0, max: 100 }),
        (userId, username, role, tokenVersion) => {
          const user: UserForToken = {
            id: String(userId),
            username,
            role,
            tokenVersion,
          };

          const token = generateToken(user);
          const decoded = jwt.verify(token, jwtSecret) as TokenPayload;

          const diff = decoded.exp! - decoded.iat!;
          expect(diff).toBeGreaterThan(0);
          expect(diff).toBeLessThanOrEqual(86400);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('exp - iat <= 86400 for shorter expiration times', () => {
    process.env.JWT_EXPIRATION = '1h';

    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 100000 }),
        fc.stringMatching(/^[a-zA-Z0-9_]{3,20}$/),
        fc.constantFrom('user', 'admin'),
        fc.integer({ min: 0, max: 100 }),
        (userId, username, role, tokenVersion) => {
          const user: UserForToken = {
            id: String(userId),
            username,
            role,
            tokenVersion,
          };

          const token = generateToken(user);
          const decoded = jwt.verify(token, jwtSecret) as TokenPayload;

          const diff = decoded.exp! - decoded.iat!;
          expect(diff).toBeGreaterThan(0);
          // Even with shorter expiration, must still be <= 86400
          expect(diff).toBeLessThanOrEqual(86400);
        }
      ),
      { numRuns: 100 }
    );
  });
});
