// Unit tests only: pure functions, no database, no supertest
// Runs with full parallelism for speed
const base = require('./jest.config');

const unitTestFiles = [
  'backup\\.property\\.test\\.ts',
  'combatMessageGenerator\\.test\\.ts',
  'compute-seedings\\.unit\\.test\\.ts',
  'cors\\.property\\.test\\.ts',
  'damageDampeners\\.test\\.ts',
  'distributeTiers\\.test\\.ts',
  'economyCalculations\\.test\\.ts',
  'stableNameGenerator\\.test\\.ts',
  'weaponSelection\\.test\\.ts',
  'envConfig\\.property\\.test\\.ts',
  'jwtService\\.test\\.ts',
  'notifications\\.property\\.test\\.ts',
  'onboardingAnalyticsService\\.test\\.ts',
  'passwordHashing\\.property\\.test\\.ts',
  'passwordService\\.test\\.ts',
  'manualRepairDiscount\\.property\\.test\\.ts',
  'manualRepairDiscount\\.test\\.ts',
  'repairCostMultiRobot\\.test\\.ts',
  'storageCalculations\\.test\\.ts',
  'streamingStudioOperatingCost\\.property\\.test\\.ts',
  'streamingStudioUpgradeCosts\\.property\\.test\\.ts',
  'tournament-bracket-seeding\\.property\\.test\\.ts',
  'validation\\.property\\.test\\.ts',
  'weapon-bonus-rebalance\\.test\\.ts',
  'kothMatchmaking\\.property\\.test\\.ts',
  'kothMatchmaking\\.test\\.ts',
  'kothOrchestrator\\.property\\.test\\.ts',
  'kothOrchestrator\\.test\\.ts',
  'kothNotification\\.property\\.test\\.ts',
  'kothStandings\\.property\\.test\\.ts',
  'kothApi\\.test\\.ts',
  'weaponProperties\\.test\\.ts',
  'weaponStatValidation\\.property\\.test\\.ts',
  'rangeBands\\.test\\.ts',
  'weaponEquipValidation\\.test\\.ts',
  'dependency-upgrade-invariants\\.property\\.test\\.ts',
  'securityValidation\\.property\\.test\\.ts',
  'schemaValidator\\.property\\.test\\.ts',
  'tokenVersion\\.property\\.test\\.ts',
  'jwtExpiration\\.property\\.test\\.ts',
  'ownership\\.property\\.test\\.ts',
  'robotSanitization\\.property\\.test\\.ts',
  'securityMonitor\\.property\\.test\\.ts',
  'securityHeaders\\.property\\.test\\.ts',
  'errorHandler\\.property\\.test\\.ts',
  'currencyConstraint\\.property\\.test\\.ts',
  'prestigeUtils\\.property\\.test\\.ts',
  'stableSanitization\\.property\\.test\\.ts',
  'adminServices\\.test\\.ts',
  'robotServices\\.test\\.ts',
  'fileValidationService\\.test\\.ts',
  'fileValidationService\\.property\\.test\\.ts',
  'contentModerationService\\.test\\.ts',
  'contentModerationService\\.property\\.test\\.ts',
  'imageProcessingService\\.test\\.ts',
  'imageProcessingService\\.property\\.test\\.ts',
  'fileStorageService\\.test\\.ts',
  'fileStorageService\\.property\\.test\\.ts',
  'pendingUploadCache\\.test\\.ts',
  'pendingUploadCache\\.property\\.test\\.ts',
  'imageUploadHandlers\\.test\\.ts',
  'imageUploadHandlers\\.property\\.test\\.ts',
  'orphanCleanupJob\\.test\\.ts',
  'orphanCleanupJob\\.property\\.test\\.ts',
  'adminUploadsHandler\\.test\\.ts',
  'adminUploadsHandler\\.property\\.test\\.ts',
  'changelogImageService\\.test\\.ts',
  'changelogImageService\\.property\\.test\\.ts',
  'generate-changelog-drafts\\.test\\.ts',
  'generate-changelog-drafts\\.property\\.test\\.ts',
];

module.exports = {
  ...base,
  setupFilesAfterEnv: ['<rootDir>/tests/setup.unit.ts'],
  testMatch: undefined,
  testRegex: `(${unitTestFiles.join('|')})$`,
  maxWorkers: '75%',
  testTimeout: 30000,
};
