// Unit tests only: pure functions, no database, no supertest
// Runs with full parallelism for speed
const base = require('./jest.config');

const unitTestFiles = [
  'backup\\.property\\.test\\.ts',
  'combatMessageGenerator\\.test\\.ts',
  'compute-seedings\\.unit\\.test\\.ts',
  'cors\\.property\\.test\\.ts',
  'damageDampeners\\.test\\.ts',
  'discounts\\.test\\.ts',
  'distributeTiers\\.test\\.ts',
  'economyCalculations\\.test\\.ts',
  'stableNameGenerator\\.test\\.ts',
  'weaponSelection\\.test\\.ts',
  'envConfig\\.property\\.test\\.ts',
  'jwtService\\.test\\.ts',
  'notifications\\.property\\.test\\.ts',
  'onboardingAnalyticsService\\.test\\.ts',
  'passwordHashing\\.property\\.test\\.ts',
  'passwordService\\.test\\.ts',
  'manualRepairDiscount\\.property\\.test\\.ts',
  'manualRepairDiscount\\.test\\.ts',
  'repairCostMultiRobot\\.test\\.ts',
  'storageCalculations\\.test\\.ts',
  'streamingStudioOperatingCost\\.property\\.test\\.ts',
  'streamingStudioUpgradeCosts\\.property\\.test\\.ts',
  'tournament-bracket-seeding\\.property\\.test\\.ts',
  'validation\\.property\\.test\\.ts',
  'weapon-bonus-rebalance\\.test\\.ts',
  'kothMatchmaking\\.property\\.test\\.ts',
  'kothMatchmaking\\.test\\.ts',
  'kothOrchestrator\\.property\\.test\\.ts',
  'kothOrchestrator\\.test\\.ts',
  'kothNotification\\.property\\.test\\.ts',
  'kothStandings\\.property\\.test\\.ts',
  'kothApi\\.test\\.ts',
  'weaponProperties\\.test\\.ts',
  'weaponStatValidation\\.property\\.test\\.ts',
  'rangeBands\\.test\\.ts',
  'weaponEquipValidation\\.test\\.ts',
  'dependency-upgrade-invariants\\.property\\.test\\.ts',
  'securityValidation\\.property\\.test\\.ts',
  'schemaValidator\\.property\\.test\\.ts',
  'tokenVersion\\.property\\.test\\.ts',
  'jwtExpiration\\.property\\.test\\.ts',
  'ownership\\.property\\.test\\.ts',
  'robotSanitization\\.property\\.test\\.ts',
  'securityMonitor\\.property\\.test\\.ts',
  'securityHeaders\\.property\\.test\\.ts',
  'errorHandler\\.property\\.test\\.ts',
  'currencyConstraint\\.property\\.test\\.ts',
  'prestigeUtils\\.property\\.test\\.ts',
  'stableSanitization\\.property\\.test\\.ts',
  'adminServices\\.test\\.ts',
  'robotServices\\.test\\.ts',
  'fileValidationService\\.test\\.ts',
  'fileValidationService\\.property\\.test\\.ts',
  'contentModerationService\\.test\\.ts',
  'contentModerationService\\.property\\.test\\.ts',
  'imageProcessingService\\.test\\.ts',
  'imageProcessingService\\.property\\.test\\.ts',
  'fileStorageService\\.test\\.ts',
  'fileStorageService\\.property\\.test\\.ts',
  'pendingUploadCache\\.test\\.ts',
  'pendingUploadCache\\.property\\.test\\.ts',
  'imageUploadHandlers\\.test\\.ts',
  'imageUploadHandlers\\.property\\.test\\.ts',
  'orphanCleanupJob\\.test\\.ts',
  'orphanCleanupJob\\.property\\.test\\.ts',
  'adminUploadsHandler\\.test\\.ts',
  'adminUploadsHandler\\.property\\.test\\.ts',
  'changelogImageService\\.test\\.ts',
  'changelogImageService\\.property\\.test\\.ts',
  'generate-changelog-drafts\\.test\\.ts',
  'generate-changelog-drafts\\.property\\.test\\.ts',
  'tuningPoolConfig\\.test\\.ts',
  'tuningPoolService\\.test\\.ts',
  'tuningCombatIntegration\\.test\\.ts',
  'tuningPracticeArena\\.test\\.ts',
  'leagueHistoryService\\.property\\.test\\.ts',
  'leagueHistoryEnrichment\\.test\\.ts',
  'adminLeagueHistory\\.test\\.ts',
  'leagueHistoryPublic\\.test\\.ts',
  'bookingOfficeMigration\\.test\\.ts',
  'subscriptionProperties\\.test\\.ts',
  'teamCoordination\\.property\\.test\\.ts',
  'teamCoordinationEffects\\.test\\.ts',
  'lockingPredicates\\.test\\.ts',
  'rosterEligibilityFilter\\.test\\.ts',
  'teamBattleEngine\\.test\\.ts',
  'teamBattleMatchmakingService\\.test\\.ts',
  'notification-service\\.test\\.ts',
  'achievementTeamBattle\\.test\\.ts',
  'teamTournamentBattleOrchestrator\\.test\\.ts',
  'teamTournamentBattleOrchestrator\\.property\\.test\\.ts',
  // Scheduling (mocked, no DB)
  'schedulingService\\.test\\.ts',
  // Arena / spatial (pure math, no DB)
  'adaptationTracker\\.property\\.test\\.ts',
  'arenaLayout\\.property\\.test\\.ts',
  'arenaLayout\\.test\\.ts',
  'positionTracker\\.property\\.test\\.ts',
  'positionTracker\\.test\\.ts',
  'pressureSystem\\.property\\.test\\.ts',
  'servoStrain\\.property\\.test\\.ts',
  'servoStrain\\.test\\.ts',
  'vector2d\\.property\\.test\\.ts',
  'vector2d\\.test\\.ts',
  // Route validation (schema-only, no DB)
  'adminRouteValidation\\.test\\.ts',
  'analyticsRouteValidation\\.test\\.ts',
  'financesRouteValidation\\.test\\.ts',
  'leaderboardsRouteValidation\\.test\\.ts',
  'onboardingRouteValidation\\.test\\.ts',
  // Config / errors / utilities (no DB)
  'env\\.test\\.ts',
  'cronValidation\\.test\\.ts',
  'AppError\\.test\\.ts',
  'domainErrors\\.test\\.ts',
  'paginationQuery\\.test\\.ts',
  'sharedFormulas\\.test\\.ts',
  'sharedRepairCostParity\\.test\\.ts',
  // KotH engine (mocked, no DB)
  'kothEngine\\.property\\.test\\.ts',
  'kothEngine\\.test\\.ts',
  // Services (mocked, no DB)
  'eventRegistry\\.test\\.ts',
  'teamBattleRewardService\\.test\\.ts',
  'teamMatchmakingUtils\\.test\\.ts',
  'tournamentService\\.property\\.test\\.ts',
  'achievementC18\\.property\\.test\\.ts',
  // Prestige / weapon refinement (mocked, no DB)
  'prestigeFeatures\\.integration\\.test\\.ts',
  'weaponRefinement\\.property\\.test\\.ts',
  'weaponRefinement\\.test\\.ts',
];

module.exports = {
  ...base,
  setupFilesAfterEnv: ['<rootDir>/tests/setup.unit.ts'],
  testMatch: undefined,
  testRegex: `(${unitTestFiles.join('|')})$`,
  maxWorkers: '75%',
  testTimeout: 30000,
};
