// Achievement configuration for the Achievement & Milestone System
// Follows the facilities.ts config pattern (exported const array with typed interface)

// --- Types ---

export type AchievementTier = 'easy' | 'medium' | 'hard' | 'very_hard' | 'secret';
export type AchievementScope = 'user' | 'robot';
export type AchievementCategory = 'combat' | 'league' | 'economy' | 'prestige' | 'style';
export type AchievementProgressType = 'numeric' | 'boolean';

export type AchievementTriggerType =
  | 'wins'
  | 'losses'
  | 'battles'
  | 'kills'
  | 'elo'
  | 'prestige'
  | 'fame'
  | 'currency'
  | 'lifetime_earnings'
  | 'streaming_revenue'
  | 'facility_count'
  | 'robot_count'
  | 'weapon_count'
  | 'league_promotion'
  | 'tournament_wins'
  | 'win_streak'
  | 'koth_wins'
  | 'tag_team_wins'
  | 'practice_battles'
  | 'onboarding'
  | 'tuning_allocated'
  | 'tuning_full'
  | 'attribute_max'
  | 'attribute_upgraded'
  | 'weapon_type'
  | 'loadout_wins'
  | 'stance_wins'
  | 'perfect_victory'
  | 'low_hp_win'
  | 'elo_upset'
  | 'yield_forced'
  | 'yield_comeback'
  | 'zero_yield_win'
  | 'no_tuning_win'
  | 'glass_cannon'
  | 'overkill'
  | 'shield_only_win'
  | 'survival_streak'
  | 'bankrupt'
  | 'demotion_repromotion'
  | 'effective_stat'
  | 'all_modes_win'
  | 'tag_in_win'
  | 'solo_carry'
  | 'lose_streak'
  | 'low_hp_survival'
  | 'battle_duration';

export interface AchievementDefinition {
  id: string;
  name: string;
  description: string;
  reference: string;
  category: AchievementCategory;
  tier: AchievementTier;
  scope: AchievementScope;
  rewardCredits: number;
  rewardPrestige: number;
  hidden: boolean;
  triggerType: AchievementTriggerType;
  triggerThreshold?: number;
  triggerMeta?: Record<string, unknown>;
  progressType: AchievementProgressType;
  progressLabel?: string;
  badgeIconFile: string;
}

// --- Reward constants ---

export const TIER_REWARDS: Record<AchievementTier, { credits: number; prestige: number }> = {
  easy: { credits: 25_000, prestige: 25 },
  medium: { credits: 50_000, prestige: 50 },
  hard: { credits: 100_000, prestige: 100 },
  very_hard: { credits: 250_000, prestige: 250 },
  secret: { credits: 50_000, prestige: 50 },
};

// --- Config array ---

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ============================================================
  // COMBAT (C1–C19) — Robot-level (except C16, C18 which are User-level)
  // ============================================================
  {
    id: 'C1',
    name: "I'll Be Back",
    description: 'Win your first battle',
    reference: 'Terminator',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'wins',
    triggerThreshold: 1,
    progressType: 'numeric',
    progressLabel: 'wins',
    badgeIconFile: 'achievement-c1',
  },
  {
    id: 'C2',
    name: 'Danger, Will Robinson!',
    description: 'Lose your first battle',
    reference: 'Lost in Space',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'losses',
    triggerThreshold: 1,
    progressType: 'numeric',
    progressLabel: 'losses',
    badgeIconFile: 'achievement-c2',
  },
  {
    id: 'C3',
    name: 'Bite My Shiny Metal Badge',
    description: 'Complete 10 battles on one robot',
    reference: 'Bender, Futurama',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'battles',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'battles',
    badgeIconFile: 'achievement-c3',
  },
  {
    id: 'C4',
    name: 'By Your Command',
    description: 'Win 25 battles on one robot',
    reference: 'Cylons, BSG',
    category: 'combat',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'wins',
    triggerThreshold: 25,
    progressType: 'numeric',
    progressLabel: 'wins',
    badgeIconFile: 'achievement-c4',
  },
  {
    id: 'C5',
    name: 'Hasta La Vista, Baby',
    description: 'Destroy an opponent (0 HP) 25 times on one robot',
    reference: 'Terminator 2',
    category: 'combat',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'kills',
    triggerThreshold: 25,
    progressType: 'numeric',
    progressLabel: 'destroyed',
    badgeIconFile: 'achievement-c5',
  },
  {
    id: 'C6',
    name: 'I Am Iron Man',
    description: 'Win 50 battles on one robot',
    reference: 'Iron Man / Marvel',
    category: 'combat',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'wins',
    triggerThreshold: 50,
    progressType: 'numeric',
    progressLabel: 'wins',
    badgeIconFile: 'achievement-c6',
  },
  {
    id: 'C7',
    name: 'Exterminate!',
    description: 'Destroy opponents 50 times on one robot',
    reference: 'Daleks, Doctor Who',
    category: 'combat',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'kills',
    triggerThreshold: 50,
    progressType: 'numeric',
    progressLabel: 'destroyed',
    badgeIconFile: 'achievement-c7',
  },
  {
    id: 'C8',
    name: 'I, Robot',
    description: 'Win 100 battles on one robot',
    reference: 'Asimov / movie',
    category: 'combat',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'wins',
    triggerThreshold: 100,
    progressType: 'numeric',
    progressLabel: 'wins',
    badgeIconFile: 'achievement-c8',
  },
  {
    id: 'C9',
    name: 'Flawless Victory',
    description: 'Win a battle with 100% HP (perfect victory)',
    reference: 'Mortal Kombat',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'perfect_victory',
    progressType: 'boolean',
    badgeIconFile: 'achievement-c9',
  },
  {
    id: 'C10',
    name: "It's Just a Flesh Wound",
    description: 'Win a battle with <10% HP remaining',
    reference: 'Monty Python',
    category: 'combat',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'low_hp_win',
    triggerMeta: { maxHpPercent: 10 },
    progressType: 'boolean',
    badgeIconFile: 'achievement-c10',
  },
  {
    id: 'C11',
    name: 'Never Tell Me the Odds',
    description: 'Win against an opponent 150+ ELO above you (league or tournament only)',
    reference: 'Han Solo, Star Wars',
    category: 'combat',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'elo_upset',
    triggerMeta: { minEloDiff: 150 },
    progressType: 'boolean',
    badgeIconFile: 'achievement-c11',
  },
  {
    id: 'C12',
    name: 'Resistance Is Futile',
    description: 'Win 10 consecutive league battles',
    reference: 'Borg, Star Trek',
    category: 'combat',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'win_streak',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'consecutive wins',
    badgeIconFile: 'achievement-c12',
  },
  {
    id: 'C13',
    name: 'Look What They Need to Mimic a Fraction of Our Power',
    description: 'Win 15 consecutive league battles',
    reference: 'Omni-Man, Invincible',
    category: 'combat',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'win_streak',
    triggerThreshold: 15,
    progressType: 'numeric',
    progressLabel: 'consecutive wins',
    badgeIconFile: 'achievement-c13',
  },
  {
    id: 'C14',
    name: 'Do You Yield?',
    description: 'Force an opponent to yield for the first time',
    reference: 'General combat trope',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'yield_forced',
    triggerThreshold: 1,
    progressType: 'boolean',
    badgeIconFile: 'achievement-c14',
  },
  {
    id: 'C15',
    name: "I Didn't Hear No Bell",
    description: 'Win a battle after losing the previous battle on the same robot',
    reference: 'Rocky / meme',
    category: 'combat',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'yield_comeback',
    progressType: 'boolean',
    badgeIconFile: 'achievement-c15',
  },
  {
    id: 'C16',
    name: 'Wax On, Wax Off',
    description: 'Fight 25 practice arena battles',
    reference: 'Karate Kid',
    category: 'combat',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'practice_battles',
    triggerThreshold: 25,
    progressType: 'numeric',
    progressLabel: 'practice battles',
    badgeIconFile: 'achievement-c16',
  },
  {
    id: 'C17',
    name: 'There Is No Spoon',
    description: 'Win a battle while having 0 tuning points allocated',
    reference: 'The Matrix',
    category: 'combat',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'no_tuning_win',
    progressType: 'boolean',
    badgeIconFile: 'achievement-c17',
  },
  {
    id: 'C18',
    name: 'Autobots, Roll Out!',
    description: 'Win at least one battle in each mode: league, KotH, tag team, and tournament',
    reference: 'Optimus Prime, Transformers',
    category: 'combat',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'all_modes_win',
    progressType: 'boolean',
    badgeIconFile: 'achievement-c18',
  },
  {
    id: 'C19',
    name: 'Peace Through Tyranny',
    description: 'Win a battle after being at <5% HP at any point during the fight',
    reference: 'Megatron, Transformers',
    category: 'combat',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'low_hp_survival',
    triggerMeta: { maxHpPercent: 5 },
    progressType: 'boolean',
    badgeIconFile: 'achievement-c19',
  },

  // ============================================================
  // LEAGUE & COMPETITION (L1–L17) — Robot-level (except L10, L11 which are User-level)
  // ============================================================
  {
    id: 'L1',
    name: 'Silver Surfer',
    description: 'Reach Silver league',
    reference: 'Marvel Comics',
    category: 'league',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'league_promotion',
    triggerMeta: { league: 'silver' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-l1',
  },
  {
    id: 'L2',
    name: 'Heart of Gold',
    description: 'Reach Gold league',
    reference: "Hitchhiker's Guide",
    category: 'league',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'league_promotion',
    triggerMeta: { league: 'gold' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-l2',
  },
  {
    id: 'L3',
    name: 'Heavy Metal',
    description: 'Reach Platinum league',
    reference: 'Music / material',
    category: 'league',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'league_promotion',
    triggerMeta: { league: 'platinum' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-l3',
  },
  {
    id: 'L4',
    name: 'Shine On You Crazy Diamond',
    description: 'Reach Diamond league',
    reference: 'Pink Floyd',
    category: 'league',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'league_promotion',
    triggerMeta: { league: 'diamond' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-l4',
  },
  {
    id: 'L5',
    name: 'We Are the Champions',
    description: 'Reach Champion league',
    reference: 'Queen',
    category: 'league',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'league_promotion',
    triggerMeta: { league: 'champion' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-l5',
  },
  {
    id: 'L6',
    name: 'King of the Hill',
    description: 'Win your first KotH match (1st place)',
    reference: 'TV show / game mode',
    category: 'league',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'koth_wins',
    triggerThreshold: 1,
    progressType: 'numeric',
    progressLabel: 'KotH wins',
    badgeIconFile: 'achievement-l6',
  },
  {
    id: 'L7',
    name: 'Lord of the Hill',
    description: 'Win 10 KotH matches (1st place)',
    reference: 'Expanded KotH reference',
    category: 'league',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'koth_wins',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'KotH wins',
    badgeIconFile: 'achievement-l7',
  },
  {
    id: 'L8',
    name: 'WALL-E and EVE',
    description: 'Win your first Tag Team battle',
    reference: 'WALL-E, Pixar',
    category: 'league',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'tag_team_wins',
    triggerThreshold: 1,
    progressType: 'numeric',
    progressLabel: 'tag team wins',
    badgeIconFile: 'achievement-l8',
  },
  {
    id: 'L9',
    name: 'The Megazord',
    description: 'Win 25 Tag Team battles',
    reference: 'Power Rangers',
    category: 'league',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'tag_team_wins',
    triggerThreshold: 25,
    progressType: 'numeric',
    progressLabel: 'tag team wins',
    badgeIconFile: 'achievement-l9',
  },
  {
    id: 'L10',
    name: 'There Can Be Only One',
    description: 'Win a tournament',
    reference: 'Highlander',
    category: 'league',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'tournament_wins',
    triggerThreshold: 1,
    progressType: 'numeric',
    progressLabel: 'tournament wins',
    badgeIconFile: 'achievement-l10',
  },
  {
    id: 'L11',
    name: 'Thunderdome',
    description: 'Win 3 tournaments',
    reference: 'Mad Max',
    category: 'league',
    tier: 'very_hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'tournament_wins',
    triggerThreshold: 3,
    progressType: 'numeric',
    progressLabel: 'tournament wins',
    badgeIconFile: 'achievement-l11',
  },
  {
    id: 'L12',
    name: 'ELO-quent',
    description: 'Reach 1400 ELO on any robot',
    reference: 'Pun on ELO + eloquent',
    category: 'league',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'elo',
    triggerThreshold: 1400,
    progressType: 'numeric',
    progressLabel: 'ELO',
    badgeIconFile: 'achievement-l12',
  },
  {
    id: 'L13',
    name: 'Over 9000!',
    description: 'Reach 1600 ELO on any robot',
    reference: 'Dragon Ball Z',
    category: 'league',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'elo',
    triggerThreshold: 1600,
    progressType: 'numeric',
    progressLabel: 'ELO',
    badgeIconFile: 'achievement-l13',
  },
  {
    id: 'L14',
    name: 'The Chosen One',
    description: 'Reach 1800 ELO on any robot',
    reference: 'The Matrix / trope',
    category: 'league',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'elo',
    triggerThreshold: 1800,
    progressType: 'numeric',
    progressLabel: 'ELO',
    badgeIconFile: 'achievement-l14',
  },
  {
    id: 'L15',
    name: "Tag, You're It!",
    description: 'Win a tag team battle where the reserve robot tagged in',
    reference: 'Playground game',
    category: 'league',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'tag_in_win',
    progressType: 'boolean',
    badgeIconFile: 'achievement-l15',
  },
  {
    id: 'L16',
    name: 'Dynamic Duo',
    description: 'Win 40 tag team battles',
    reference: 'Batman & Robin',
    category: 'league',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'tag_team_wins',
    triggerThreshold: 40,
    progressType: 'numeric',
    progressLabel: 'tag team wins',
    badgeIconFile: 'achievement-l16',
  },
  {
    id: 'L17',
    name: 'I Work Alone',
    description: 'Win a tag team battle where your active robot destroyed both opponents without tagging out',
    reference: 'Batman / lone wolf trope',
    category: 'league',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'solo_carry',
    progressType: 'boolean',
    badgeIconFile: 'achievement-l17',
  },

  // ============================================================
  // ECONOMY & STABLE (E1–E17) — User-level
  // ============================================================
  {
    id: 'E1',
    name: 'Hello World',
    description: 'Complete onboarding',
    reference: 'Programming',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'onboarding',
    progressType: 'boolean',
    badgeIconFile: 'achievement-e1',
  },
  {
    id: 'E2',
    name: 'The Odds Are 725 to 1',
    description: 'Earn ₡100,000 total from battles',
    reference: 'C-3PO, Star Wars',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'lifetime_earnings',
    triggerThreshold: 100_000,
    progressType: 'numeric',
    progressLabel: 'credits earned',
    badgeIconFile: 'achievement-e2',
  },
  {
    id: 'E3',
    name: 'Show Me the Money',
    description: 'Accumulate ₡5,000,000 in your balance at once',
    reference: 'Jerry Maguire',
    category: 'economy',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'currency',
    triggerThreshold: 5_000_000,
    progressType: 'numeric',
    progressLabel: 'balance',
    badgeIconFile: 'achievement-e3',
  },
  {
    id: 'E4',
    name: 'Scrooge McDuck',
    description: 'Earn ₡25,000,000 lifetime from all sources',
    reference: 'DuckTales',
    category: 'economy',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'lifetime_earnings',
    triggerThreshold: 25_000_000,
    progressType: 'numeric',
    progressLabel: 'lifetime credits',
    badgeIconFile: 'achievement-e4',
  },
  {
    id: 'E5',
    name: 'Buy the Dip',
    description: 'Purchase your first weapon',
    reference: 'Finance meme',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'weapon_count',
    triggerThreshold: 1,
    progressType: 'boolean',
    badgeIconFile: 'achievement-e5',
  },
  {
    id: 'E6',
    name: 'Arsenal',
    description: 'Own 10 weapons simultaneously',
    reference: 'Military / football club',
    category: 'economy',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'weapon_count',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'weapons',
    badgeIconFile: 'achievement-e6',
  },
  {
    id: 'E7',
    name: 'Mall Cop',
    description: 'Buy your first shield',
    reference: 'Paul Blart / pun',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'weapon_type',
    triggerMeta: { weaponType: 'shield' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-e7',
  },
  {
    id: 'E8',
    name: 'Pimp My Bot',
    description: 'Upgrade any robot attribute for the first time',
    reference: 'Pimp My Ride',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'attribute_upgraded',
    progressType: 'boolean',
    badgeIconFile: 'achievement-e8',
  },
  {
    id: 'E9',
    name: 'Fully Operational',
    description: 'Reach an effective stat of 50 on any attribute on a robot',
    reference: 'Death Star, Star Wars',
    category: 'economy',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'effective_stat',
    triggerThreshold: 50,
    progressType: 'boolean',
    badgeIconFile: 'achievement-e9',
  },
  {
    id: 'E10',
    name: 'The Architect',
    description: 'Own 3 facilities at level 3+',
    reference: 'The Matrix',
    category: 'economy',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'facility_count',
    triggerThreshold: 3,
    triggerMeta: { minLevel: 3 },
    progressType: 'numeric',
    progressLabel: 'facilities at L3+',
    badgeIconFile: 'achievement-e10',
  },
  {
    id: 'E11',
    name: 'Megacorp',
    description: 'Own 5 facilities at level 3+',
    reference: 'Sci-fi trope',
    category: 'economy',
    tier: 'very_hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'facility_count',
    triggerThreshold: 5,
    triggerMeta: { minLevel: 3 },
    progressType: 'numeric',
    progressLabel: 'facilities at L3+',
    badgeIconFile: 'achievement-e11',
  },
  {
    id: 'E12',
    name: 'Skynet Is Online',
    description: 'Own 3 robots simultaneously',
    reference: 'Terminator',
    category: 'economy',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'robot_count',
    triggerThreshold: 3,
    progressType: 'numeric',
    progressLabel: 'robots',
    badgeIconFile: 'achievement-e12',
  },
  {
    id: 'E13',
    name: 'Robot Army',
    description: 'Own 5 robots simultaneously',
    reference: 'General sci-fi',
    category: 'economy',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'robot_count',
    triggerThreshold: 5,
    progressType: 'numeric',
    progressLabel: 'robots',
    badgeIconFile: 'achievement-e13',
  },
  {
    id: 'E14',
    name: 'Rise of the Machines',
    description: 'Own 7 robots simultaneously',
    reference: 'Terminator 3',
    category: 'economy',
    tier: 'very_hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'robot_count',
    triggerThreshold: 7,
    progressType: 'numeric',
    progressLabel: 'robots',
    badgeIconFile: 'achievement-e14',
  },
  {
    id: 'E15',
    name: 'Fine-Tuned Machine',
    description: 'Allocate tuning points on any robot for the first time',
    reference: 'Common phrase / Tuning Bay',
    category: 'economy',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'tuning_allocated',
    progressType: 'boolean',
    badgeIconFile: 'achievement-e15',
  },
  {
    id: 'E16',
    name: 'Overclocked',
    description: 'Allocate 50+ tuning points on a single robot',
    reference: 'PC gaming term',
    category: 'economy',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'tuning_full',
    triggerThreshold: 50,
    progressType: 'numeric',
    progressLabel: 'tuning points',
    badgeIconFile: 'achievement-e16',
  },
  {
    id: 'E17',
    name: 'Bankrupt!',
    description: 'Have your balance drop below ₡0 from daily operating costs',
    reference: 'Monopoly / economy',
    category: 'economy',
    tier: 'secret',
    scope: 'user',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'bankrupt',
    progressType: 'boolean',
    badgeIconFile: 'achievement-e17',
  },

  // ============================================================
  // PRESTIGE & FAME (P1–P10) — Mixed level (P1-P4, P9-P10: User; P5-P8: Robot)
  // ============================================================
  {
    id: 'P1',
    name: 'Established',
    description: 'Reach 1,000 prestige',
    reference: 'Prestige rank title',
    category: 'prestige',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'prestige',
    triggerThreshold: 1_000,
    progressType: 'numeric',
    progressLabel: 'prestige',
    badgeIconFile: 'achievement-p1',
  },
  {
    id: 'P2',
    name: 'Veteran',
    description: 'Reach 5,000 prestige',
    reference: 'Prestige rank title',
    category: 'prestige',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'prestige',
    triggerThreshold: 5_000,
    progressType: 'numeric',
    progressLabel: 'prestige',
    badgeIconFile: 'achievement-p2',
  },
  {
    id: 'P3',
    name: 'Elite',
    description: 'Reach 10,000 prestige',
    reference: 'Prestige rank title',
    category: 'prestige',
    tier: 'very_hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'prestige',
    triggerThreshold: 10_000,
    progressType: 'numeric',
    progressLabel: 'prestige',
    badgeIconFile: 'achievement-p3',
  },
  {
    id: 'P4',
    name: 'Legendary',
    description: 'Reach 25,000 prestige',
    reference: 'Prestige rank title',
    category: 'prestige',
    tier: 'very_hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'prestige',
    triggerThreshold: 25_000,
    progressType: 'numeric',
    progressLabel: 'prestige',
    badgeIconFile: 'achievement-p4',
  },
  {
    id: 'P5',
    name: '15 Minutes of Fame',
    description: 'Robot reaches 100 fame',
    reference: 'Andy Warhol quote',
    category: 'prestige',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'fame',
    triggerThreshold: 100,
    progressType: 'numeric',
    progressLabel: 'fame',
    badgeIconFile: 'achievement-p5',
  },
  {
    id: 'P6',
    name: 'Famous Last Words',
    description: 'Robot reaches 500 fame',
    reference: 'Common phrase',
    category: 'prestige',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'fame',
    triggerThreshold: 500,
    progressType: 'numeric',
    progressLabel: 'fame',
    badgeIconFile: 'achievement-p6',
  },
  {
    id: 'P7',
    name: 'Legendary Status',
    description: 'Robot reaches 2,500 fame',
    reference: 'Fame tier',
    category: 'prestige',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'fame',
    triggerThreshold: 2_500,
    progressType: 'numeric',
    progressLabel: 'fame',
    badgeIconFile: 'achievement-p7',
  },
  {
    id: 'P8',
    name: 'Mythical Proportions',
    description: 'Robot reaches 5,000 fame',
    reference: 'Fame tier',
    category: 'prestige',
    tier: 'very_hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.very_hard.credits,
    rewardPrestige: TIER_REWARDS.very_hard.prestige,
    hidden: false,
    triggerType: 'fame',
    triggerThreshold: 5_000,
    progressType: 'numeric',
    progressLabel: 'fame',
    badgeIconFile: 'achievement-p8',
  },
  {
    id: 'P9',
    name: 'Influencer',
    description: 'Earn ₡100,000 total streaming revenue',
    reference: 'Modern culture',
    category: 'prestige',
    tier: 'easy',
    scope: 'user',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'streaming_revenue',
    triggerThreshold: 100_000,
    progressType: 'numeric',
    progressLabel: 'streaming revenue',
    badgeIconFile: 'achievement-p9',
  },
  {
    id: 'P10',
    name: 'Content Creator',
    description: 'Earn ₡1,000,000 total streaming revenue',
    reference: 'Modern culture',
    category: 'prestige',
    tier: 'hard',
    scope: 'user',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'streaming_revenue',
    triggerThreshold: 1_000_000,
    progressType: 'numeric',
    progressLabel: 'streaming revenue',
    badgeIconFile: 'achievement-p10',
  },

  // ============================================================
  // STYLE & QUIRKY (S1–S14) — Robot-level (except S13 which is User-level)
  // ============================================================
  {
    id: 'S1',
    name: 'Bleep Bloop',
    description: 'Equip a robot with an energy weapon',
    reference: 'Robot stereotype',
    category: 'style',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'weapon_type',
    triggerMeta: { weaponType: 'energy' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s1',
  },
  {
    id: 'S2',
    name: 'Get to the Choppa',
    description: 'Equip a robot with a ballistic weapon',
    reference: 'Predator / Arnold',
    category: 'style',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'weapon_type',
    triggerMeta: { weaponType: 'ballistic' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s2',
  },
  {
    id: 'S3',
    name: 'Sword Art Online',
    description: 'Equip a robot with a melee weapon',
    reference: 'Anime series',
    category: 'style',
    tier: 'easy',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.easy.credits,
    rewardPrestige: TIER_REWARDS.easy.prestige,
    hidden: false,
    triggerType: 'weapon_type',
    triggerMeta: { weaponType: 'melee' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s3',
  },
  {
    id: 'S4',
    name: 'Dual Wielding Intensifies',
    description: 'Win 10 battles with dual-wield loadout',
    reference: 'Gaming meme',
    category: 'style',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'loadout_wins',
    triggerThreshold: 10,
    triggerMeta: { loadoutType: 'dual_wield' },
    progressType: 'numeric',
    progressLabel: 'dual-wield wins',
    badgeIconFile: 'achievement-s4',
  },
  {
    id: 'S5',
    name: 'Turtle Mode Activated',
    description: 'Win 10 battles on defensive stance',
    reference: 'Gaming strategy',
    category: 'style',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'stance_wins',
    triggerThreshold: 10,
    triggerMeta: { stance: 'defensive' },
    progressType: 'numeric',
    progressLabel: 'defensive wins',
    badgeIconFile: 'achievement-s5',
  },
  {
    id: 'S6',
    name: 'LEEROY JENKINS!',
    description: 'Win 10 battles on offensive stance',
    reference: 'WoW meme',
    category: 'style',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'stance_wins',
    triggerThreshold: 10,
    triggerMeta: { stance: 'offensive' },
    progressType: 'numeric',
    progressLabel: 'offensive wins',
    badgeIconFile: 'achievement-s6',
  },
  {
    id: 'S7',
    name: 'Perfectly Balanced',
    description: 'Win 10 battles on balanced stance',
    reference: 'Thanos, Avengers',
    category: 'style',
    tier: 'medium',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'stance_wins',
    triggerThreshold: 10,
    triggerMeta: { stance: 'balanced' },
    progressType: 'numeric',
    progressLabel: 'balanced wins',
    badgeIconFile: 'achievement-s7',
  },
  {
    id: 'S8',
    name: 'No Retreat, No Surrender',
    description: 'Win a battle with yield threshold set to 0%',
    reference: 'Movie title / phrase',
    category: 'style',
    tier: 'hard',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.hard.credits,
    rewardPrestige: TIER_REWARDS.hard.prestige,
    hidden: false,
    triggerType: 'zero_yield_win',
    progressType: 'boolean',
    badgeIconFile: 'achievement-s8',
  },
  {
    id: 'S9',
    name: 'Glass Cannon',
    description: 'Deal 500+ damage in a battle but finish with <5% HP',
    reference: 'RPG archetype',
    category: 'style',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'glass_cannon',
    triggerMeta: { minDamage: 500, maxHpPercent: 5 },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s9',
  },
  {
    id: 'S10',
    name: 'Overkill',
    description: 'Win a battle in under 5 seconds',
    reference: 'Gaming term',
    category: 'style',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'battle_duration',
    triggerMeta: { maxSeconds: 5 },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s10',
  },
  {
    id: 'S11',
    name: 'R2-D2 Would Be Proud',
    description: 'Win a tag team battle as the reserve robot (tagged in to save the day)',
    reference: 'Star Wars',
    category: 'style',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'tag_in_win',
    triggerMeta: { role: 'reserve' },
    progressType: 'boolean',
    badgeIconFile: 'achievement-s11',
  },
  {
    id: 'S12',
    name: 'Johnny 5 Is Alive!',
    description: 'Have a robot survive 50 battles (totalBattles minus times destroyed ≥ 50)',
    reference: 'Short Circuit',
    category: 'style',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'survival_streak',
    triggerThreshold: 50,
    progressType: 'numeric',
    progressLabel: 'battles survived',
    badgeIconFile: 'achievement-s12',
  },
  {
    id: 'S13',
    name: "Dead or Alive, You're Coming With Me",
    description: 'Force 10 opponents to yield (cumulative, any robot)',
    reference: 'RoboCop',
    category: 'style',
    tier: 'medium',
    scope: 'user',
    rewardCredits: TIER_REWARDS.medium.credits,
    rewardPrestige: TIER_REWARDS.medium.prestige,
    hidden: false,
    triggerType: 'yield_forced',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'yields forced',
    badgeIconFile: 'achievement-s13',
  },
  {
    id: 'S14',
    name: 'Brain the Size of a Planet',
    description: 'Lose 10 battles in a row on a single robot',
    reference: "Marvin, Hitchhiker's Guide",
    category: 'style',
    tier: 'secret',
    scope: 'robot',
    rewardCredits: TIER_REWARDS.secret.credits,
    rewardPrestige: TIER_REWARDS.secret.prestige,
    hidden: true,
    triggerType: 'lose_streak',
    triggerThreshold: 10,
    progressType: 'numeric',
    progressLabel: 'consecutive losses',
    badgeIconFile: 'achievement-s14',
  },
];

// --- Helpers ---

export function getAchievementById(id: string): AchievementDefinition | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}

export function getAchievementsByTriggerType(type: AchievementTriggerType): AchievementDefinition[] {
  return ACHIEVEMENTS.filter((a) => a.triggerType === type);
}
