/**
 * Shared test data for PracticeArenaPage tests
 */

export const mockUser = {
  id: 1,
  username: 'testplayer',
  email: 'test@example.com',
  role: 'player',
  currency: 500_000,
  prestige: 100,
  stableName: 'Test Stable',
};

export const mockRobots = [
  {
    id: 1,
    name: 'Iron Fist',
    elo: 1500,
    currentHP: 80,
    maxHP: 100,
    currentShield: 50,
    maxShield: 50,
    loadoutType: 'single',
    stance: 'balanced',
    yieldThreshold: 20,
    mainWeaponId: 1,
    offhandWeaponId: null,
    imageUrl: null,
    combatPower: 10,
    targetingSystems: 8,
    criticalSystems: 5,
    penetration: 7,
    weaponControl: 6,
    attackSpeed: 9,
    armorPlating: 8,
    shieldCapacity: 5,
    evasionThrusters: 4,
    damageDampeners: 3,
    counterProtocols: 6,
    hullIntegrity: 7,
    servoMotors: 5,
    gyroStabilizers: 4,
    hydraulicSystems: 6,
    powerCore: 8,
    combatAlgorithms: 7,
    threatAnalysis: 5,
    adaptiveAI: 6,
    logicCores: 4,
    syncProtocols: 3,
    supportSystems: 2,
    formationTactics: 3,
  },
  {
    id: 2,
    name: 'Steel Thunder',
    elo: 1400,
    currentHP: 100,
    maxHP: 100,
    currentShield: 30,
    maxShield: 50,
    loadoutType: 'weapon_shield',
    stance: 'defensive',
    yieldThreshold: 15,
    mainWeaponId: 2,
    offhandWeaponId: 3,
    imageUrl: null,
    combatPower: 5,
    targetingSystems: 5,
    criticalSystems: 5,
    penetration: 5,
    weaponControl: 5,
    attackSpeed: 5,
    armorPlating: 5,
    shieldCapacity: 5,
    evasionThrusters: 5,
    damageDampeners: 5,
    counterProtocols: 5,
    hullIntegrity: 5,
    servoMotors: 5,
    gyroStabilizers: 5,
    hydraulicSystems: 5,
    powerCore: 5,
    combatAlgorithms: 5,
    threatAnalysis: 5,
    adaptiveAI: 5,
    logicCores: 5,
    syncProtocols: 5,
    supportSystems: 5,
    formationTactics: 5,
  },
];


export const mockSparringPartners = [
  {
    botTier: 'WimpBot',
    description: 'Weak opponent with level 1 attributes',
    attributeLevel: 1,
    priceTier: { min: 0, max: 99999 },
    loadoutOptions: ['single', 'weapon_shield', 'two_handed', 'dual_wield'],
    rangeBandOptions: ['melee', 'short', 'mid', 'long'],
    stanceOptions: ['offensive', 'defensive', 'balanced'],
  },
  {
    botTier: 'AverageBot',
    description: 'Average opponent with level 5 attributes',
    attributeLevel: 5,
    priceTier: { min: 100000, max: 250000 },
    loadoutOptions: ['single', 'weapon_shield', 'two_handed', 'dual_wield'],
    rangeBandOptions: ['melee', 'short', 'mid', 'long'],
    stanceOptions: ['offensive', 'defensive', 'balanced'],
  },
  {
    botTier: 'ExpertBot',
    description: 'Expert opponent with level 10 attributes',
    attributeLevel: 10,
    priceTier: { min: 250000, max: 400000 },
    loadoutOptions: ['single', 'weapon_shield', 'two_handed', 'dual_wield'],
    rangeBandOptions: ['melee', 'short', 'mid', 'long'],
    stanceOptions: ['offensive', 'defensive', 'balanced'],
  },
  {
    botTier: 'UltimateBot',
    description: 'Ultimate opponent with level 15 attributes',
    attributeLevel: 15,
    priceTier: { min: 400000, max: Infinity },
    loadoutOptions: ['single', 'weapon_shield', 'two_handed', 'dual_wield'],
    rangeBandOptions: ['melee', 'short', 'mid', 'long'],
    stanceOptions: ['offensive', 'defensive', 'balanced'],
  },
];
